/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0650c23b49c7303ea6de391be95583ba)
interface __BaseEnv_Env {
	OBJECTS: R2Bucket;
	GRAFT_REMOTE_TOKEN: string;
	REPOSITORIES: DurableObjectNamespace<import("./src/index").RepositoryDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RepositoryDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GRAFT_REMOTE_TOKEN">> {}
}
