[package]
name = "graft-tool"
version = "0.13.0"
edition = "2024"
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
rust-version = { workspace = true }
autobins = false

[[bin]]
name = "graft"
path = "src/main.rs"

[dependencies]
graft = { path = "../graft" }
graft-sdk = { path = "../graft-sdk" }
graft-sqlite = { path = "../graft-sqlite" }

anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
rusqlite = { workspace = true, features = ["bundled"] }
serde_json = "1.0"
tempfile = { workspace = true }

[lints]
workspace = true
