export const SHORT_CODES = [
  {
    code: "graft_import",
    dest: "/docs/guides/export-sqlite/#use-external-sqlite-tools",
  },
];

export const DOC_REDIRECTS = {
  "/docs/get-started/cli/": "/docs/quickstart/cli/",
  "/docs/get-started/sqlite-extension/": "/docs/quickstart/cli/",
  "/docs/quickstart/sqlite-extension/": "/docs/quickstart/cli/",
  "/docs/reference/pragmas/": "/docs/reference/cli/",
  "/docs/get-started/usage-guide/": "/docs/quickstart/app-state-walkthrough/",
  "/docs/guides/cloudflare-remote/": "/docs/guides/http-remote/",
  "/docs/concepts/app-state-versioning/": "/docs/graft-book/",
  "/docs/concepts/repository-model/": "/docs/graft-book/repository-and-objects/",
  "/docs/concepts/sqlite-snapshots/": "/docs/graft-book/sqlite-snapshots/",
  "/docs/concepts/file-artifacts/": "/docs/graft-book/repository-and-objects/",
  "/docs/concepts/row-diffs-and-merge-policy/": "/docs/graft-book/diff-and-merge/",
  "/docs/concepts/branches-and-remotes/": "/docs/graft-book/remotes-and-recovery/",
  "/docs/internals/architecture/": "/docs/graft-book/",
  "/docs/internals/object-formats/": "/docs/graft-book/repository-and-objects/",
  "/docs/internals/snapshot-storage-lsns/": "/docs/graft-book/sqlite-snapshots/",
  "/docs/internals/row-diff-engine/": "/docs/graft-book/diff-and-merge/",
  "/docs/concepts/physical-files-volumes/": "/docs/graft-book/sqlite-snapshots/",
  "/docs/concepts/snapshots-lsn/": "/docs/graft-book/sqlite-snapshots/",
  "/docs/concepts/diffs/": "/docs/graft-book/diff-and-merge/",
  "/docs/concepts/remotes-branches/": "/docs/graft-book/remotes-and-recovery/",
  "/docs/internals/architecture-v2/": "/docs/graft-book/",
  "/docs/internals/repository-mode-v2/": "/docs/graft-book/",
  "/docs/internals/graft-objects/": "/docs/graft-book/repository-and-objects/",
  "/docs/internals/snapshot-objects-v2/": "/docs/graft-book/repository-and-objects/",
  "/docs/internals/row-diff-v2/": "/docs/graft-book/diff-and-merge/",
  "/docs/internals/http-remote-protocol/": "/docs/reference/remote-protocol/",
  "/zh/docs/get-started/cli/": "/zh/docs/quickstart/cli/",
  "/zh/docs/get-started/sqlite-extension/": "/zh/docs/quickstart/cli/",
  "/zh/docs/quickstart/sqlite-extension/": "/zh/docs/quickstart/cli/",
  "/zh/docs/reference/pragmas/": "/zh/docs/reference/cli/",
  "/zh/docs/get-started/usage-guide/": "/zh/docs/quickstart/app-state-walkthrough/",
  "/zh/docs/guides/cloudflare-remote/": "/zh/docs/guides/http-remote/",
  "/zh/docs/concepts/app-state-versioning/": "/zh/docs/graft-book/",
  "/zh/docs/concepts/repository-model/": "/zh/docs/graft-book/repository-and-objects/",
  "/zh/docs/concepts/sqlite-snapshots/": "/zh/docs/graft-book/sqlite-snapshots/",
  "/zh/docs/concepts/file-artifacts/": "/zh/docs/graft-book/repository-and-objects/",
  "/zh/docs/concepts/row-diffs-and-merge-policy/": "/zh/docs/graft-book/diff-and-merge/",
  "/zh/docs/concepts/branches-and-remotes/": "/zh/docs/graft-book/remotes-and-recovery/",
  "/zh/docs/internals/architecture/": "/zh/docs/graft-book/",
  "/zh/docs/internals/object-formats/": "/zh/docs/graft-book/repository-and-objects/",
  "/zh/docs/internals/snapshot-storage-lsns/": "/zh/docs/graft-book/sqlite-snapshots/",
  "/zh/docs/internals/row-diff-engine/": "/zh/docs/graft-book/diff-and-merge/",
  "/zh/docs/concepts/physical-files-volumes/": "/zh/docs/graft-book/sqlite-snapshots/",
  "/zh/docs/concepts/snapshots-lsn/": "/zh/docs/graft-book/sqlite-snapshots/",
  "/zh/docs/concepts/diffs/": "/zh/docs/graft-book/diff-and-merge/",
  "/zh/docs/concepts/remotes-branches/": "/zh/docs/graft-book/remotes-and-recovery/",
  "/zh/docs/internals/architecture-v2/": "/zh/docs/graft-book/",
  "/zh/docs/internals/repository-mode-v2/": "/zh/docs/graft-book/",
  "/zh/docs/internals/graft-objects/": "/zh/docs/graft-book/repository-and-objects/",
  "/zh/docs/internals/snapshot-objects-v2/": "/zh/docs/graft-book/repository-and-objects/",
  "/zh/docs/internals/row-diff-v2/": "/zh/docs/graft-book/diff-and-merge/",
  "/zh/docs/internals/http-remote-protocol/": "/zh/docs/reference/remote-protocol/",
} as const;
