#!/usr/bin/env bash
set -euo pipefail

USAGE=$(
    cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --client ID   Specify an ID to identify this client. Default = "default"
  --release     Build/run in release mode.
  --trace       Enable trace-level logging for graft.
  --log PATH    Output logs to a file
  --gdb         Run sqlite3 under gdb debugger.
  --autosync    Enable automatic background sync.
  --s3 BUCKET   Connect the loader default remote to the provided S3 bucket.
EOF
)

GIT_ROOT="$(git rev-parse --show-toplevel)"

TARGET="debug"
BUILD_FLAGS=""

GDB=${GDB:-0}
export RUST_LOG=${RUST_LOG:-warn}

CLIENT_ID="default"
DATA_ROOT="${GIT_ROOT}/target/graft-sqlite-shell"
REMOTE_TYPE="fs"
REMOTE_ROOT="${DATA_ROOT}/remote"
REMOTE_BUCKET=""
LOG_FILE=""
AUTOSYNC=""

# parse flags
while [[ $# -gt 0 ]]; do
    case $1 in
        --client)
            shift
            CLIENT_ID="$1"
            shift
            ;;
        --release)
            shift
            TARGET="release"
            BUILD_FLAGS="--release"
            ;;
        --trace)
            shift
            export RUST_LOG="graft_sqlite=trace,graft=trace"
            ;;
        --log)
            shift
            LOG_FILE="$1"
            export NO_COLOR=1
            shift
            ;;
        --gdb)
            shift
            export GDB=1
            ;;
        --autosync)
            shift
            AUTOSYNC=60
            ;;
        --s3)
            shift
            REMOTE_TYPE="s3_compatible"
            REMOTE_BUCKET="${1}"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "${USAGE}"
            exit 1
            ;;
    esac
done

CLIENT_ROOT="${DATA_ROOT}/clients/${CLIENT_ID}"
DATA_DIR="${CLIENT_ROOT}/data"
CONFIG_PATH="${CLIENT_ROOT}/graft.toml"

mkdir -p "${REMOTE_ROOT}" "${DATA_DIR}"
cat >"${CONFIG_PATH}" <<EOF
data_dir = "${DATA_DIR}"
EOF

if [ -n "${LOG_FILE}" ]; then
    cat >>"${CONFIG_PATH}" <<EOF
log_file = "${LOG_FILE}"
EOF
fi

if [ -n "${AUTOSYNC}" ]; then
    cat >>"${CONFIG_PATH}" <<EOF
autosync = ${AUTOSYNC}
EOF
fi

case "${REMOTE_TYPE}" in
    fs)
        cat >>"${CONFIG_PATH}" <<EOF

[remote]
type = "fs"
root = "${REMOTE_ROOT}"
EOF
        ;;
    s3_compatible)
        cat >>"${CONFIG_PATH}" <<EOF

[remote]
type = "s3_compatible"
bucket = "${REMOTE_BUCKET}"
EOF
        ;;
    *)
        echo "unsupported remote type: ${REMOTE_TYPE}" >&2
        exit 1
        ;;
esac

cargo build ${BUILD_FLAGS} --package graft-ext
just run sqlite bin --version >/dev/null

# Discover the path to the VFS depending on platform
LIB_PATH="${GIT_ROOT}/target/${TARGET}"
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    LIB_PATH="${LIB_PATH}/graft_ext.dll"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    LIB_PATH="${LIB_PATH}/libgraft_ext.dylib"
else
    LIB_PATH="${LIB_PATH}/libgraft_ext.so"
fi

ARGS=(
    -header
    -table
    -cmd '.log stderr'
    -cmd ".load '${LIB_PATH}'"
    -cmd ".open 'file:main?vfs=graft'"
)

cd "${CLIENT_ROOT}"
exec "${GIT_ROOT}/tasks/sqlite/bin" "${ARGS[@]}"
